import type { Metadata } from "next";
import { Montserrat } from "next/font/google";
import localFont from "next/font/local";
import { GSAPWrapper } from "./components/features/wrappers/GSAPWrapper";
import { Header } from "./components/layout/Header";
import "./globals.css";

const montserrat = Montserrat({
  subsets: ["latin"],
  display: "swap",
});

const ivyPresto = localFont({
  src: "../public/font/ivyPresto.ttf",
  variable: "--font-ivy",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${montserrat.className} ${ivyPresto.variable} antialiased`}
      >
        <Header />
        <GSAPWrapper>{children}</GSAPWrapper>
      </body>
    </html>
  );
}
